In [ ]:
Ans = 1
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_ variable:", type(list_))
print("Data type of array_list variable:", type(array_list))

Data type of list_ variable: <class 'list'>
Data type of array_list variable: <class 'numpy.ndarray'>


In [ ]:
Ans = 2
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# print data type of each element in list_
for elem in list_:
    print("Data type of element", elem, "in list_ variable:", type(elem))

# print data type of each element in array_list
for elem in array_list:
    print("Data type of element", elem, "in array_list variable:", type(elem))

output:
Data type of element 1 in list_ variable: <class 'str'>
Data type of element 2 in list_ variable: <class 'str'>
Data type of element 3 in list_ variable: <class 'str'>
Data type of element 4 in list_ variable: <class 'str'>
Data type of element 5 in list_ variable: <class 'str'>
Data type of element 1 in array_list variable: <class 'numpy.str_'>
Data type of element 2 in array_list variable: <class 'numpy.str_'>
Data type of element 3 in array_list variable: <class 'numpy.str_'>
Data type of element 4 in array_list variable: <class 'numpy.str_'>
Data type of element 5 in array_list variable: <class 'numpy.str_'>
    

In [ ]:
Ans = 3
array_list = np.array(object=list_, dtype=int)

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# print data type of each element in list_
for elem in list_:
    print("Data type of element", elem, "in list_ variable:", type(elem))

# print data type of each element in array_list
for elem in array_list:
    print("Data type of element", elem, "in array_list variable:", type(elem))

    
output:
Data type of element 1 in list_ variable: <class 'str'>
Data type of element 2 in list_ variable: <class 'str'>
Data type of element 3 in list_ variable: <class 'str'>
Data type of element 4 in list_ variable: <class 'str'>
Data type of element 5 in list_ variable: <class 'str'>
Data type of element 1 in array_list variable: <class 'numpy.int64'>
Data type of element 2 in array_list variable: <class 'numpy.int64'>
Data type of element 3 in array_list variable: <class 'numpy.int64'>
Data type of element 4 in array_list variable: <class 'numpy.int64'>
Data type of element 5 in array_list variable: <class 'numpy.int64'>
    

In [ ]:
Ans = 4
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# print shape of num_array
print("Shape of num_array:", num_array.shape)

# print size of num_array
print("Size of num_array:", num_array.size)

output:
Shape of num_array: (2, 3)
Size of num_array: 6
    

In [ ]:
Ans = 5
import numpy as np

# create a 3x3 array containing zeros
zeros_array = np.zeros(shape=(3, 3))

# print the zeros array
print(zeros_array)

output:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
    
    

In [ ]:
Ans = 6
import numpy as np

# create a 5x5 identity matrix
identity_matrix = np.identity(n=5)

# print the identity matrix
print(identity_matrix)

output:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
    